pluginManagement {

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.equals('robothy-platform-release')) {
                useModule("com.robothy:platform-release-gradle-plugin:${robothyPlatformReleaseGradlePluginVersion}")
            }
        }
    }

    repositories {
        mavenLocal()

        maven {
            url = 'https://maven.pkg.github.com/robothy-platform/maven'
            credentials {
                username = settings.hasProperty("GITHUB_USERNAME") ? settings.getProperty("GITHUB_USERNAME") : (System.getenv("GITHUB_USERNAME") ?: "")
                password = settings.hasProperty("GITHUB_TOKEN") ? settings.getProperty("GITHUB_TOKEN") : (System.getenv("GITHUB_TOKEN") ?: "")
            }
        }

        gradlePluginPortal()

        maven {
            url = 'https://maven.aliyun.com/repository/gradle-plugin'
        }
    }
}

rootProject.name = 'netty-http-router'

