name: Build
on:
  push:
    branches:
      - main

jobs:
  gralde-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        id: build
        run: |
          pwd
          ls -l
          git log --pretty=format:"%H - %an, %aI : %s" -5
          chmod +x gradlew
          ./gradlew build