name: Build
on:
  push:
    branches:
      - main

jobs:
  gralde-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Setup JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'

      - name: Build and test
        id: release
        run: |
          pwd
          ls -l
          git log --pretty=format:"%H - %an, %aI : %s" -5
          chmod +x gradlew
          ./gradlew build