name: PR Build
on:
  push:
    branches:
      - main

jobs:
  publish-to-maven:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Build and test
        id: release
        run: |
          pwd
          ls -l
          git log --pretty=format:"%H - %an, %aI : %s" -5
          chmod +x gradlew
          ./gradlew build