name: Release
on:
  push:
    branches: [ 'main' ]

jobs:
  publish-to-maven:
    runs-on: ubuntu-20.04
    env:
      GITHUB_USERNAME: Robothy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        id: release
        run: |
          pwd
          ls -l
          git log --pretty=format:"%H - %an, %aI : %s" -5
          export PUBLISH_VERSION=`awk -F '=' '$1=="version" {print substr($2, 0, index($2, "-")-1)}' gradle.properties`
          echo ''
          echo ::set-output name=PUBLISH_VERSION::(echo $PUBLISH_VERSION)
          echo ::set-output name=PUBLISH_VERSION1::(echo ${PUBLISH_VERSION})
          echo publishing version $PUBLISH_VERSION
          export NEXT_VERSION=`echo $PUBLISH_VERSION | awk '{print substr($1, 0, match($1, /\.[0-9]*$/)) substr($1, match($1, /\.[0-9]*$/)+1)+1"-SNAPSHOT"}'`
          echo next version $NEXT_VERSION
          awk -F '=' -v next_version="$NEXT_VERSION" '{ if ($1 == "version") print $1"="next_version; else print $1"="$2}' gradle.properties > gradle.properties.tmp
          mv gradle.properties.tmp gradle.properties
          cat gradle.properties

      - name: Commit next version
        uses: EndBug/add-and-commit@v9
        with:
          add: './gradle.properties'
          author_name: GitHub Actions
          author_email: bot@robothy.com
          message: ${{steps.release.outputs.PUBLISH_VERSION}} released ${{steps.release.outputs.PUBLISH_VERSION1}}.
          push: true