name: Release

on:
  workflow_dispatch:
    inputs:
      gradleLogLevel:
        description: 'Gradle logging level.'
        required: false
        default: Warn
        type: choice
        options:
          - Info
          - Warn
          - Debug
          - Stacktrace

jobs:
  release:
    runs-on: ubuntu-24.04
    env:
      GITHUB_USERNAME: Robothy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{runner.os}}-build-gradle-${{hashFiles('**/gradle-wrapper.properties')}}

      - name: Prepare parameters
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/gradle.properties <<EOF
          GITHUB_USERNAME=Robothy
          signing.secretKey=${{ secrets.SING_SECRET_KEY }}
          signing.password=${{ secrets.SIGN_PASSWORD }}
          MAVEN_CENTRAL_PORTAL_USERNAME=${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_PORTAL_PASSWORD=${{ secrets.OSSRH_PASSWORD }}
          EOF

      - name: Update release version
        run: ./gradlew releaseVersion

      - name: Release
        run: |
          LEVEL=$(echo "${{inputs.gradleLogLevel}}" | tr '[:upper:]' '[:lower:]')
          ./gradlew check release uploadMavenCentralPortal nextSnapshotVersion --$LEVEL
